apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka
  creationTimestamp: null
  labels:
    run: xgboost
  name: xgboost
spec:
  replicas: 1
  selector:
    matchLabels:
      run: xgboost
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: xgboost
    spec:
      containers:
      - image: xgboost:latest
        imagePullPolicy: IfNotPresent
        name: xgboost
        ports:
          - containerPort: 8078
        resources: {}
status: {}
