apiVersion: v1
kind: Pod
metadata:
  namespace: kafka
  name: cdn-webserver
  labels:
    run: cdn-webserver
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: cdn-webserver
      image: cdn-webserver:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "0.5"
      ports:
        - containerPort: 7079
      volumeMounts:
        - mountPath: "/usr/data"
          name: task-pv-storage
