apiVersion: v1
kind: Pod
metadata:
  namespace: kafka
  name: cdn-webserver
  labels:
    run: cdn-webserver
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: cdn-webserver
      image: cloudxprt/cdn-webserver:v1.00
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 7079
      volumeMounts:
        - mountPath: "/usr/data"
          name: task-pv-storage
